version: '3'

services:
  # Postgres runner
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    ports:
      - 5432
    container_name: "base-db"

  # Client
  bot:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/src
    links:
      - db
    container_name: "base-bot"
